name: Deploy no AWS com Terraform

on:
  push:
    branches:
      - main # Substitua pela branch que deseja acionar o fluxo de trabalho

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        run: |
          aws configure set aws_access_key_id ${{ secrets.aws_access_key_id }}
          aws configure set aws_secret_access_key ${{ secrets.aws_secret_access_key }}
          aws configure set region us-east-1

      - name: Inicializar Terraform
        run: |
          cd ../workflow/.github
          terraform init

      - name: Planejar a infraestrutura
        run: |
          cd ../workflow/.github
          terraform plan

      - name: Aplicar a infraestrutura
        run: |
          cd ../workflow/.github
          terraform apply -auto-approve
